app:
  name: auth-server
  description: User Authentication Server

server:
  port: 9100

  ## 인증 유형 : LOCAL
  #    type: LOCAL
  #    url: http://127.0.0.1:9100
  ## 인증 유형 : KEYCLOAK
  type: KEYCLOAK
  url: http://127.0.0.1:8180
  realm: default
  master-realm: master
  free-ipa-url: https://127.0.0.1/ipa/session
  free-ipa-referer: https://{DOMAIN}}/ipa